# Offline training configuration for bandit environment
env: "bandit"
envs: 100000
hists: 1
samples: 1
H: 100
dim: 10
var: 0.0
cov: 0.0

# Model configuration
embd: 32
head: 1
layer: 3
lr: 0.001
dropout: 0
shuffle: false

# Training configuration
num_epochs: 1000
seed: 0